/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swmem_org_sltran_GRTClass */

#ifndef _Included_swmem_org_sltran_GRTClass
#define _Included_swmem_org_sltran_GRTClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swmem_org_sltran_GRTClass
 * Method:    getHelloNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swmem_org_sltran_GRTClass_getHelloNDKString
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_swmem_org_sltran_GRTClass_loadModule
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
